# Generated by Django 4.1.7 on 2023-08-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_account_age_alter_account_created_alter_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='age',
        ),
    ]
